### ISSUE TITLE
trap tool

### ISSUE THREAD

**Issue by pretech86** [mrf345/retrap#4]
thanks for the tool but can you take a look on trap tool 
https://github.com/jofpin/trape

thanks a lot

**Comment by mrf345** [comment]
Most welcome. I did check out `trape` before, but never managed to get it working on my OS.
I think it's broken, and it hasn't been maintained for quite some time now.

I opened a PR there once https://github.com/jofpin/trape/pull/221
but didn't get much attention. So i thought it will be faster and easier to just create another tool.
